Fix type error in `lib/standalone.js`
```
lib/standalone.js(339,12): error TS2339: Property 'name' does not exist on type 'Object'.
lib/standalone.js(340,64): error TS2345: Argument of type 'Object' is not assignable to parameter of type 'StylelintCssSyntaxError'.
  The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
    Type 'Object' is missing the following properties from type 'StylelintCssSyntaxError': column, input, line, message, and 3 more.
```