Fix `--print-config` description in CLI help
The `--print-config` option never requires an argument. For example:

```console
$ bin/stylelint.js --print-config -c scripts/visual-config.json scripts/visual.css
{
  "rules": {
...
```

On the other hand, the following example is mistaken:

```console
$ bin/stylelint.js --print-config scripts/visual-config.json
Error: No configuration provided for /Users/masafumi.koba/git/stylelint/stylelint/scripts/visual-config.json
...
```