fix(types): remove unused type import
This type import was added in https://github.com/stylelint/stylelint/pull/6356, but during code review that PR was refactored to obviate the `file-entry-cache` types in the public API. The import was never removed. Keeping the import here results in [compilation errors](https://app.circleci.com/pipelines/github/palantir/blueprint/3156/workflows/9eda97ec-3a2f-4aa6-aa6c-89d5b65b8491/jobs/61694) for downstream consumers:

```
../../node_modules/stylelint/types/stylelint/index.d.ts:5:39 - error TS7016: Could not find a declaration file for module 'file-entry-cache'. '/home/circleci/project/node_modules/file-entry-cache/cache.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/file-entry-cache` if it exists or add a new declaration (.d.ts) file containing `declare module 'file-entry-cache';`

5  import type * as fileEntryCache from 'file-entry-cache'
```

@jeddy3 @kimulaco