Refactor `mergeTestDescriptions()` test utility to migrate to ESM (#7035)
`mergeTestDescriptions()` is used by deprecated rules.
So I've created this commit from the `v16` branch, instead of the `main` branch.

This change enables the `esModuleInterop` flag to prevent the following TypeScript error:

```
lib/testUtils/mergeTestDescriptions.mjs:1:8 - error TS1259: Module '"/Users/masafumi.koba/git/stylelint/stylelint/node_modules/deepmerge/index"' can only be default-imported using the 'esModuleInterop' flag

1 import merge from 'deepmerge';
         ~~~~~

  node_modules/deepmerge/index.d.ts:20:1
    20 export = deepmerge;
       ~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```