Refactor to prevent unexpected mutation of shared objects
TypeScript's `Readonly*` types can prevent a mistake like this:

```js
lib/reference/units.mjs:67:17 - error TS2339: Property 'add' does not exist on type 'ReadonlySet<string>'.

67 resolutionUnits.add('foo');
                   ~~~
```