Fix rule message function type to not require users to handle all kind of arguments (#6147)
Fix rule message function type to not require users to handle all kinds of arguments

Currently, users writing custom rules and using `RuleMessageFunc` are required to handle all kinds of parameters with TypeScript's strict mode enabled. e.g.

```ts
const messages = utils.ruleMessages(ruleName, {
  invalid: (rule: string) =>
    `Failed to extract namespace from ${rule}. material/no-unused-` +
    `imports Stylelint rule likely needs to be updated.`,
});

// results in
tools/stylelint/no-unused-import.ts:7:12 - error TS2322: Type '(rule: string) => string' is not assignable to type 'string | RuleMessageFunc'.
  Type '(rule: string) => string' is not assignable to type 'RuleMessageFunc'.
    Types of parameters 'rule' and 'args' are incompatible.
      Type 'string | number | boolean | RegExp' is not assignable to type 'string'.

7   invalid: (rule: string) =>
             ~~~~~~~~~~~~~~~~~
8     `Failed to extract namespace from ${rule}. material/no-unused-` +
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
9     `imports Stylelint rule likely needs to be updated.`,
```

This can be observed in my small playground as well:

https://www.typescriptlang.org/play?#code/C4TwDgpgBASgrgGwgWQgZzQQwOYQGJwB2AxlALxQAUAdLZgE7ZoBcVaw9AlodlAD6wI2AKIAPMAEoA2gF0J5AHxR2XHgG4AUBoBmRYsE4B7QlAC2IABIQEkepV0lW8JKgw58e+QG8AvlvNWNhB2lPSIEABymKYQrCrc2PJkSgAGAILAUGFIUAAkXtmR0RA+UJxoUNqYnAgJAIQpEmpAA

We fix this by tricking TypeScript into checking rule message functions
bivariantly compared to them being checked contravariantly with strict
function types. This allows users to e.g. narrow rule message parameters
to just `string`, while also keeping a good default constraint union
type for non-explicitly typed parameters.

ds