Fix type errors in `lib/utils/report.js` and add `StylelintWarningOptions` type
```
lib/utils/report.js(37,9): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(40,13): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(40,39): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(46,33): error TS2339: Property 'positionBy' does not exist on type 'Object'.
lib/utils/report.js(48,13): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(48,49): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(49,25): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(49,70): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(65,32): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(67,14): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(68,10): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(95,38): error TS2339: Property 'stylelint' does not exist on type 'Object'.
lib/utils/report.js(97,9): error TS2339: Property 'warn' does not exist on type 'Object'.
```