Fix inconsistent error messages when module is not found
This fixes inconsistent error messages when a module is not found with `dynamicImport()`.

`dynamicImport()` now accepts an optional parameter to customize the error message.

New messages align with the error message thrown by `getCustomSyntax()` and remove verbose "Caused by" output.

We can verify the message change by the shell command.

```shell
node -e 'import("./lib/utils/getCustomSyntax.mjs").then(m => m.default("foo"))'
```

Before:

```
Error: Cannot resolve custom syntax module "foo". Check that module "foo" is available and spelled correctly.

Caused by: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'foo' imported from /Users/masafumi.koba/git/stylelint/stylelint/lib/utils/dynamicImport.mjs
    at Module.getCustomSyntax (file:///Users/masafumi.koba/git/stylelint/stylelint/lib/utils/getCustomSyntax.mjs:31:11) {
  [cause]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'foo' imported from /Users/masafumi.koba/git/stylelint/stylelint/lib/utils/dynamicImport.mjs
      at Object.getPackageJSONURL (node:internal/modules/package_json_reader:314:9)
      ...
```

After:

```
Error: Cannot resolve custom syntax module "foo". Check that module "foo" is available and spelled correctly
    at file:///Users/masafumi.koba/git/stylelint/stylelint/lib/utils/dynamicImport.mjs:21:10
    at async Module.getCustomSyntax (file:///Users/masafumi.koba/git/stylelint/stylelint/lib/utils/getCustomSyntax.mjs:16:14)
```