Fix failed tests when a `.stylelintrc` file exists in the home directory
Summary
-------

By default `cosmiconfig` search a `.stylelintrc` file up to the home directory.
Thus, in test environments which include `.stylelintrc` in their home directory, some tests fail.

This commit fixes the failed tests, by setting the project root to `stopDir` option of `cosmiconfig` on test only.
About `stopDir` option, please see <https://github.com/davidtheclark/cosmiconfig#stopdir>.

Reproduction
------------

1. Create the following `Dockerfile`

    ```Dockerfile
    FROM node:6

    RUN git clone --depth=1 https://github.com/stylelint/stylelint.git /root/stylelint

    WORKDIR /root/stylelint

    RUN npm install

    # Failed when "${HOME}/.stylelintrc" exists
    RUN echo '{"rules":{}}' > /root/.stylelintrc && \
        $(npm bin)/jest lib/__tests__/standalone.test.js

    # Passed when "${HOME}/.stylelintrc" doesn't exists
    RUN $(npm bin)/jest lib/__tests__/standalone.test.js
    ```

2. Run `docker build .` command

    ```
    ● standalone with config locatable from process.cwd not file › two warning

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 0

      323 |
      324 |   it("two warning", () => {
    > 325 |     expect(results[0].warnings.length).toBe(2);
          |                                        ^
      326 |   });
      327 |
      328 |   it("first correct warning", () => {

      at Object.it (lib/__tests__/standalone.test.js:325:40)

    ● standalone with config locatable from process.cwd not file › first correct warning

    TypeError: Cannot read property 'text' of undefined

      328 |   it("first correct warning", () => {
      329 |     expect(
    > 330 |       results[0].warnings[0].text.indexOf("Unexpected empty block")
          |       ^
      331 |     ).not.toBe(-1);
      332 |   });
      333 |

      at Object.it (lib/__tests__/standalone.test.js:330:7)

    ● standalone with config locatable from process.cwd not file › second correct warning

    TypeError: Cannot read property 'text' of undefined

      333 |
      334 |   it("second correct warning", () => {
    > 335 |     expect(results[0].warnings[1].text.indexOf("foo")).not.toBe(-1);
          |            ^
      336 |   });
      337 | });
      338 |

      at Object.it (lib/__tests__/standalone.test.js:335:12)

    Test Suites: 1 failed, 1 total
    Tests:       3 failed, 31 passed, 34 total
    Snapshots:   0 total
    Time:        2.629s
    Ran all test suites matching /lib\/__tests__\/standalone.test.js/i.
    ```